# For more info on HTTP files go to https://aka.ms/vs/httpfile
@BaseApiUrl=http://localhost:7274/api

// Users

POST {{BaseApiUrl}}/users
Content-Type: application/json
{ 
  "UserId": "B8343EAF-6C20-4A40-BADA-168FF5CEEC89",
  "FirstNames": "Craig",
  "LastName": "McLellen",
  "StockItems": [
    {
      "Symbol": "MSFT"
    },
    {
      "Symbol": "AAPL"
    }
  ]
}

###

GET {{BaseApiUrl}}/users/B8343EAF-6C20-4A40-BADA-168FF5CEEC89

###

// Stock Prices

POST {{BaseApiUrl}}/stock-prices
Content-Type: application/json
{
  "symbol": "MSFT",
  "close": 222,
  "createdDateUtc": "2025-02-24T00:00:00"
}

###

POST {{BaseApiUrl}}/stock-prices/fetch
Content-Type: application/json
{
    "symbol": "MSFT",
    "close": 222,
    "createdDateUtc": "2025-02-24T00:00:00"
}

###

// Stock History

GET {{BaseApiUrl}}/stock-prices/history