name: api

on:
  push:
    paths:
      - "API/**"
      - ".github/workflows/api.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  AZURE_RESOURCEGROUP_NAME: "rg-ezstocks-dev-aue"
  ACTIONS_STEP_DEBUG: true
  DOTNET_VERSION: 9.x
  CONFIGURATION: Release

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: API
    environment: dev
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            API/

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore --no-cache --force

      - name: Build
        run: dotnet build --configuration ${{env.CONFIGURATION}} --no-restore

      - name: Run tests
        run: dotnet test --no-build --no-restore --verbosity normal

      - name: Publish
        run: dotnet publish --configuration ${{env.CONFIGURATION}} --output ./publish --no-restore

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: "func-ezstocks-dev-aue"
          package: "./API/publish"
